#!/bin/bash
# Migration: Enhanced Hardware Controls for MacBook Pro M1
# Adds brightness controls, keyboard backlight, and enhanced audio interface support
# Generated by Hive Mind Collective Intelligence System

echo "==> Installing Enhanced Hardware Controls for MacBook Pro M1"

# Ensure new scripts are executable
chmod +x ~/.local/share/omarchy/install/config/hardware-detection.sh
chmod +x ~/.local/share/omarchy/bin/omarchy-cmd-unified-brightness
chmod +x ~/.local/share/omarchy/bin/omarchy-cmd-enhanced-audio
chmod +x ~/.local/share/omarchy/bin/omarchy-test-hardware-controls
chmod +x ~/.local/share/omarchy/bin/omarchy-cmd-brightness-menu

echo "==> Running hardware detection for MacBook Pro M1"
# Create hardware configuration directory
mkdir -p ~/.config/omarchy

# Run hardware detection
~/.local/share/omarchy/install/config/hardware-detection.sh

echo "==> Testing hardware controls"
# Run basic hardware tests
~/.local/share/omarchy/bin/omarchy-test-hardware-controls --basic

echo "==> Refreshing configurations"
# Refresh omarchy configurations to pick up new bindings
if command -v omarchy-refresh-config >/dev/null 2>&1; then
    omarchy-refresh-config
fi

# Refresh Hyprland configuration if running
if pgrep -x Hyprland >/dev/null 2>&1; then
    hyprctl reload >/dev/null 2>&1 || true
fi

# Restart SwayOSD if running
if pgrep -x swayosd-server >/dev/null 2>&1; then
    pkill swayosd-server
    sleep 1
    swayosd-server &
fi

echo "✅ Enhanced hardware controls installed successfully"
echo ""
echo "🔧 Available commands:"
echo "  omarchy-cmd-unified-brightness    - Unified brightness control"
echo "  omarchy-cmd-enhanced-audio        - Enhanced audio control"
echo "  omarchy-test-hardware-controls    - Hardware validation tests"
echo "  omarchy-cmd-brightness-menu       - Interactive brightness menu"
echo ""
echo "📋 Hardware capabilities detected:"
if [[ -f ~/.config/omarchy/hardware.conf ]]; then
    source ~/.config/omarchy/hardware.conf
    echo "  System: ${SYSTEM_PRODUCT:-Unknown}"
    echo "  Apple Silicon: ${IS_APPLE_SILICON:-false}"
    echo "  Internal brightness: ${INTERNAL_BACKLIGHT:-false}"
    echo "  External Apple display: ${EXTERNAL_APPLE_DISPLAY:-false}"
    echo "  Keyboard backlight: ${KEYBOARD_BACKLIGHT:-false}"
    echo "  Audio system: ${AUDIO_SYSTEM:-none}"
    echo "  System ready: ${SYSTEM_READY:-false}"
fi
echo ""
echo "🧪 Run 'omarchy-test-hardware-controls --interactive' to test all features"